---
Shells:
- name: Bash
  default: true
  tool: false
  type: Shell
  image:
    name: bash
    version: latest
  posix: true
  spec:
    secrets:
    - source: fromFile
      params:
        type: json
- name: Zsh
  default: true
  tool: false
  type: Shell
  image:
    name: zshusers/zsh
    version: latest
  posix: false
  spec:
    secrets:
    - source: fromFile
      params:
        type: json
        path: null
    - source: fromUrl
      params:
        type: https
        url: null
    theme: agnoster
    framework: oh-my-zsh
    plugins:
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    zstyle:
      # identify configuration for zstyle definition
      - name: ZSH_THEME
        value: agnoster
      - name: ZSH_AUTOSUGGESTIONS
        value: true
      - name: ZSH_SYNTAX_HIGHLIGHTING
        value: true
- name: BusyBox
  default: true
  tool: true
  type: Shell
  image: busybox
  posix: true
  spec:
    secrets:
    - source: fromFile
      params:
        type: json
        names: []
    - source: fromUrl
      type: https
      url: null
      params: {}
      ## add the params object accordinly
      # params:
      #   cert: |
      #     certData
      #   key: |
      #     keyData
      #   ca: |
      #     caData
      #   username: user
      #   password: password
    config:
      theme: null
      framework: null
      plugins: []