# shells: Configure your dot
# name
## shell name
# posix
## true if shell is posix compliant
# config
# define shell configuration
# config.theme
# shell theme
# config.framework
## shell framework
# config.plugins
## list of shell plugins, installed through shell framework, or manually
# secrets
## define secret sources (getFromEnv, getFromFile, getFromUrl)
---
shells:
  - name: bash
    posix: true
    secrets:
      - source: getFromEnv
        name: KEY
      - source: getFromFile
        type: json
        name: KEY
      - source: getFromUrl
        type: https
          cert: n/a
          key: n/a
          ca: n/a
        name: KEY
    config:
      theme: robbyrussel
      framework: oh-my-bash
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: zsh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-zsh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      zstyle:
        # identify configuration for zstyle definition
        - name: ZSH_THEME
          value: agnoster
        - name: ZSH_AUTOSUGGESTIONS
          value: true
        - name: ZSH_SYNTAX_HIGHLIGHTING
          value: true
  - name: fish
    posix: false
    config:
      theme: robbyrussell
      framework: oh-my-fish
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: powershell
    posix: false
    config:
      theme: agnoster
      framework: oh-my-posh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: cmd
    posix: false
    config:
      theme: agnoster
      framework: oh-my-cmd
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: pwsh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-pwsh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: sh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-sh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: csh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-csh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: tcsh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-tcsh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: ksh
    posix: false
    config:
      theme: agnoster
      framework: oh-my-ksh
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - name: dash
    posix: false
    config:
      theme: agnoster
      framework: oh-my-dash
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
